services:
  ollama:
    build: ./model
    container_name: laak-model
    networks:
      - laak_network
    ports:
      - 11434:11434
    volumes:
      - model-laak:/ollama
    entrypoint: ["/usr/bin/bash", "/start.sh"]
  backend:
    build: ./backend
    networks:
      - laak_network
    container_name: laak-backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    networks:
      - laak_network
    container_name: laak-frontend
    ports:
      - "3000:3000"

networks:
  laak_network:
      
volumes:
   model-laak:
    driver: local