services:
  # ollama:
  #   build: ./model/ollama
  #   container_name: laak-model
  #   networks:
  #     - laak_network
  #   ports:
  #     - 11434:11434
  #   volumes:
  #     - model-laak:/root/.ollama
  #   entrypoint: ["/usr/bin/bash", "/start.sh"]
  qwen:
    build: ./model/qwen
    container_name: laak-model-qwen
    networks:
      - laak_network
    ports:
      - 11434:11434
    volumes:
      - model-laak:/ollama
    entrypoint: ["/usr/bin/bash", "/start.sh"]
  backend:
    build: ./backend
    networks:
      - laak_network
    container_name: laak-backend
    ports:
      - "5000:5000"
    # depends_on:
    #   - ollama
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    networks:
      - laak_network
    container_name: laak-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  laak_network:
      
volumes:
   model-laak:
    driver: local